### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by charleskoehl** [LeisureLink-FE/ll-theme#1]
In the style tweaks branch that was merged to master yesterday, I had added the following to the top of appwide-styles.css, and used them in the .btnDefault and .btnPrimary classes. Note the addition of "button" to the beginning of each variable.

```
:root {
  --button-default_color: var(--ll-white, #fff);
  --button-default_color-hover: var(--ll-grey-light, hsla(0, 0%, 0%, 0.05));
  --button-primary_color: var(--ll-blue, hsl(203, 100%, 33%));
  --button-primary_color-hover: var(--ll-dark-blue, hsl(203, 100%, 22%));
}
```

I think those should be moved to this theme.

**Comment by uniqname** [comment]
Moved these into `ll-theme` repo. Does anything else need to be done in this branch to full integrate it, or do the references already exist?

**Comment by charleskoehl** [comment]
This theme defines .btn, .btnDefault, and .btnPrimary, but they are also defined in ih-v2 appwide-styles.css.

I think those should be removed from ih-v2, and that the .btn class should be moved into :root here as a custom variable, and then @apply'd to btnDefault and btnPrimary

**Comment by charleskoehl** [comment]
Also, the 4 custom vars of .btn should be removed.
